### ISSUE TITLE
JSON Format: negative numbers

### ISSUE THREAD

**Issue by sbrunov** [consulo/consulo-javascript#13]
Hello!

## Context
* Consulo 1.0 #1240.
* JavaScript plugin #1470.

## Problem

It seems the plugin does not parse the negative numbers properly. For example, for the following JSON object:

```json
{
    "batchSize": -1
}
```
the "expression expected" message is shown and the space right after the colon is highlighted as an error.

## References:
1. The grammar of numbers: [RFC 7159 — The JavaScript Object Notation (JSON) Data Interchange Format, page 7](https://tools.ietf.org/html/rfc7159#page-7).

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Thanks

**Comment by sbrunov** [comment]
@VISTALL, thank you!
Have just checked: the negative number (`-1`) is handled properly.

Best regards,
Sergey Brunov.
