### ISSUE TITLE
Function keyword can parsed as name

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-javascript#14]
```js

var test = {
  function: function() {
    console.log("test")
  }
}


test.function();
```

![](http://klikr.org/93195de448c384513b2cc70bd311.png)

Code is valid

**Comment by sbrunov** [comment]
Hello, @VISTALL!

It seems the `throw` property is also considered as a keyword:

```js
var expect = function(obj) {
    to: {
        throw: {
        }
    }
};
```

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
I think its a global issue, when keywords can be used as name

**Comment by VISTALL** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

# Reserved word usage

**Comment by VISTALL** [comment]
About throw. NodeJS failed with throw code
