### ISSUE TITLE
Javascript in string constants

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javascript#18]
I have long Java string constants with javascript code in them. Is there a way to highlight them somehow?

With highlighting enabled by either automatically detecting if text in a string conforms to some language rules (which may be unreliable) or by marking string constant with some annotation or Javadoc comment with some keyword.

I remember IDEA had such a highlighting feature (though I don't remember how it was triggered).

**Comment by VISTALL** [comment]
Alt + Enter inside string -> Inject Language/Reference

**Comment by unv-unv** [comment]
Pressed Alt+Enter:
![alt enter_inside_string_constant](https://user-images.githubusercontent.com/16825982/29744080-d3c7fa3c-8aa5-11e7-90a9-4c790f8474b0.png)

**Comment by VISTALL** [comment]
Try to install **IntelliLang** plugin

**Comment by unv-unv** [comment]
Thanks. With IntelliLang it works.

**Comment by VISTALL** [comment]
ah. This plugin is pain. It's provide api for injections but not provide implementation(java plugin hold implementation for it).

I think - I will move it to platform.

Thanks anyway
