### ISSUE TITLE
Support for "for..of" statement

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javascript#21]
The following valid code is highlighted with many errors in Consulo:

`function fireListener(listeners, callbackArgument)
{
    for (let listener of listeners)
    {
        listener.call(callbackArgument);
    }
}`

![изображение](https://user-images.githubusercontent.com/16825982/84266002-73ec5400-ab2c-11ea-9f90-fd7f3afd2174.png)

![изображение](https://user-images.githubusercontent.com/16825982/84266032-7ea6e900-ab2c-11ea-9f54-2e042dd56aac.png)

**Comment by unv-unv** [comment]
Using JavaScript plugin 2796 (from latest nightly build) — for..of is still highlighted as errorneous.

**Comment by VISTALL** [comment]
I pushed some notificator about change js version. But there an option for changing JS version in Project Structure (client js extension) - select EcmaScript 6

If Consulo drop this extension - can you say how u use it(which framework, etc). here 

![](https://klikr.org/e124aa81427bc78ddac35a05b850.png)

**Comment by unv-unv** [comment]
Thanks, after selecting Default Version and updating to latest nightly build it worked.

About usage. I use it with just plain JavaScript — no React/Angular/etc.
