### ISSUE TITLE
Add support for "for...in" loop

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javascript#23]
for...in is one of initial JavaScript type of loops. Need to add support for it:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

![изображение](https://user-images.githubusercontent.com/16825982/84734907-dae58f00-afaa-11ea-93ad-2f746396cd36.png)

**Comment by VISTALL** [comment]
Sorry i broke that. Fixed

**Comment by unv-unv** [comment]
Still "for" is highlighted with message "'for' statement doesn't loop"

![изображение](https://user-images.githubusercontent.com/16825982/84743003-fb691580-afb9-11ea-9366-cf569c1eefad.png)

**Comment by VISTALL** [comment]
It's inspection code - i can't reproduce in simple example.

Maybe you have 'break' in first { } block, which mean - it will walk one time (and no more)

**Comment by unv-unv** [comment]
Ah, I see. Yes, this block has return inside. Inspection is correct.
