### ISSUE TITLE
JavaScript Code Style lacks examples

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javascript#25]
There're many options for JavaScript code style. But provided code sample is too short to show all the options.

![изображение](https://user-images.githubusercontent.com/16825982/84837789-a1139780-b041-11ea-9529-ff36096366f9.png)

**Comment by VISTALL** [comment]
Hello. I added bigger example. Without classes - i think need split this config to EcmaScript options (idk for now)
