### ISSUE TITLE
Strange behavior of curly braces in JavaScript Code Style

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javascript#26]
Opening curly brace for switch is shifted and curly brace after "do" in do...while is not on next line.

![изображение](https://user-images.githubusercontent.com/16825982/84901646-731b6b00-b0b4-11ea-9c77-136a940d31f0.png)

**Comment by VISTALL** [comment]
It's wrong settings page (it's for do {} <new-line> while). Anyway - brace option not handled, wip

**Comment by VISTALL** [comment]
pushed
