### ISSUE TITLE
Support class expressions in ES6

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javascript#35]
In class expression class name may be omitted (but may be present):
```
class Foo
{
}

Foo.Bar = class Bar
{
};

Foo.Baz = class extends Foo
{
};
```
ES6 grammar in Consulo now doesn't support class expression and highlights them as errors:
![изображение](https://user-images.githubusercontent.com/16825982/144753658-560e99ee-4da4-4b86-9825-3355efb5da39.png)

**Comment by unv-unv** [comment]
Still shows syntactic error:
![изображение](https://user-images.githubusercontent.com/16825982/145697657-8141a551-de34-4816-9e64-3fa0a6b553e6.png)

**Comment by VISTALL** [comment]
ops. done

**Comment by unv-unv** [comment]
Now it doesn't support anonymous class expressions:
![изображение](https://user-images.githubusercontent.com/16825982/145710375-028d9db8-add8-4aa0-a819-34dc29ac9342.png)

**Comment by VISTALL** [comment]
fixed
