### ISSUE TITLE
Disable some JS inspections by default

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javascript#53]
Предлагаю отключить по умолчанию следующие инспекции:

JavaScript / Code style issues / Chained function call
(highlights chained function calls as errors — as if in Java were highlighted new StringBuilder().append().append()...)

JavaScript / Code style issues / Nested function call
(same as previous)

JavaScript / Potentially confusing code constructs / Conditional expression
(highlights ternary operators usage as errors)

JavaScript / JavaScript function metrics / Function with many return points
(highligths more than one return in function as error; in present days it is debatable if single return with cumbersome code is better than several simple returns)

It is better to turn these inspections off by default.

**Comment by VISTALL** [comment]
fixed in 687b91d04d4b16097e703c1760caf6d79648321d
